import sys
sys.stdin = open("24_4710.txt")
s = input()
a =[]
s = s.replace("CA","X")
s = s.replace("CO","X")
s = s.replace("DA","X")
s = s.replace("DO","X")
s = s.replace("FA","X")
s = s.replace("FO","X")
s = s.replace("AX","A X")
s = s.replace("CX","C X")
s = s.replace("DX","D X")
s = s.replace("FX","F X")
s = s.replace("XA","X A")
s = s.replace("XC","X C")
s = s.replace("XD","X D")
s = s.replace("XF","X F")
print(max(map(len,s.split())))